### ISSUE TITLE
Unable to create a shema containing an array of numbers

### ISSUE THREAD

**Issue by sirlancelot** [yoitsro/joigoose#21]
Versions:

```
joigoose@4.0.0
joi@13.1.1
mongoose@5.0.2
```

Reproduction Steps:

```javascript
const Mongoose = require("mongoose")
const Joi = require("joi")
const Joigoose = require("joigoose")(Mongoose)

const schema = Joi.object({
    numbers: Joi.array().items(Joi.number())
})

Joigoose.convert(schema)
// TypeError: Undefined type `undefined` at `validate.isAsync`
//   Did you try nesting Schemas? You can only nest using refs or arrays.
//     at Function.Schema.interpretAsType ([...]/node_modules/mongoose/lib/schema.js:599:11)
//     at Schema.path ([...]/node_modules/mongoose/lib/schema.js:456:29)
//     at Schema.add ([...]/node_modules/mongoose/lib/schema.js:337:12)
//     at Schema.add ([...]/node_modules/mongoose/lib/schema.js:326:14)
//     at new Schema ([...]/node_modules/mongoose/lib/schema.js:89:10)
//     at Object.internals.typeDeterminer ([...]/node_modules/joigoose/lib/index.js:194:17)
//     at Object.internals.convert ([...]/node_modules/joigoose/lib/index.js:116:27)
//     at [...]/node_modules/joigoose/lib/index.js:86:37
//     at Array.forEach (<anonymous>)
//     at Object.internals.convert ([...]/node_modules/joigoose/lib/index.js:84:31)
//     at repl:1:10
```

**Comment by sirlancelot** [comment]
Any recommendations, @yoitsro?

**Comment by yoitsro** [comment]
Hey @sirlancelot. I don't have much time to take a look at this right now, but I'd welcome a PR with accompanying tests. Rubbish response, I know, but I'm super busy right now :(
